BoxLayoutCal:

<BoxLayoutCal@BoxLayout>:
    orientation:"vertical"
    size:root.width, root.height

    TextInput:
        id: display_label
        text:"0"
        halign:"right"
        font_size:"30dp"
        size_hint:1,2
        readonly: True  # Disable string input

             
       
    BoxLayout:
        orientation:"horizontal"
        
        Button:
            text:"%"
            on_press:root.percentage()
            
        Button:
            id: clear_entry
            text:"CE"
            on_press:root.clear_entry()
        Button:
            id: clear
            text:"C"
            on_press: root.clear()
        Button:
            id: clear_entry
            text:"<--"
            on_press:root.clear_entry()
            
    BoxLayout:
        orientation:"horizontal"
        
        Button:
            text:"1/x"
            on_press:root.rational()
        Button:
            text:"x^2"
            on_press:root.square()
        Button:
            text:"x^(1/2)"
            on_press:root.squareroot()
        Button:
            text:"÷"
            on_press:root.math_sign("÷")
    BoxLayout:
        orientation:"horizontal"
        
        Button:
            text:"7"
            on_press: root.button_press(7)
        Button:
            text:"8"
            on_press: root.button_press(8)
        Button:
            text:"9"
            on_press: root.button_press(9)
        Button:
            text:"x"
            on_press:root.math_sign("x")
    BoxLayout:
        orientation:"horizontal"
        
        Button:
            text:"4"
            on_press: root.button_press(4)
        Button:
            text:"5"
            on_press: root.button_press(5)
        Button:
            text:"6"
            on_press: root.button_press(6)
        Button:
            text:"-"
            on_press: root.math_sign("-")
    BoxLayout:
        orientation:"horizontal"
        
        Button:
            text:"1"
            on_press: root.button_press(1)
        Button:
            text:"2"
            on_press: root.button_press(2)
        Button:
            text:"3"
            on_press: root.button_press(3)
        Button:
            text:"+"
            on_press: root.math_sign("+")
    BoxLayout:
        orientation:"horizontal"
        
        Button:
            text:"+/-"
            on_press:root.sign()
        Button:
            text:"0"
            on_press: root.button_press(0)
        Button:
            text:"."
            on_press:root.dot()
        Button:
            text:"="
            on_press: root.equals()